dns:
  provider: {}
oidc:
  adminGroupID: someAdminGroupID
  clientID: someClientID
  clientSecret: someClientSecret
  issuer: https://login.microsoftonline.com/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  scope: openid email profile
  teamAdminGroupID: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  tenantID: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  subClaimMapper: oid
  clientSecret: somesecretvalue
otomi:
  adminPassword: somePassword
  version: master
